# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8aa907ae52b7be0eb392385474f4d225203d3ca817d66d2f36bc938019ac3dd298930e7002fda303afde7a6ed1b83d64c1c1cbf4f718493a0a671f6a913cb102

test:
  secret_key_base: 60ed73a718704b59fc898853d1f118fa0bf8d407300ac606a7b57922837744abbaae0dc0d1a4f96af19b9cec2672858e58729c4129e809b15a907bd023adf32a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
